
name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      service_dir:
        required: true
        type: string
      commit_short:
        required: true
        type: string

run-name: "Build and Push ${{ inputs.service_name }}"

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo "${{ vars.DOCKER_AUTH_TOKEN }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        working-directory: ${{ inputs.service_dir }}
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/${{ inputs.service_name }}:${{ inputs.commit_short }} -t ${{ vars.DOCKER_USERNAME }}/${{ inputs.service_name }}:latest .
          docker push ${{ vars.DOCKER_USERNAME }}/${{ inputs.service_name }}:${{ inputs.commit_short }}
          docker push ${{ vars.DOCKER_USERNAME }}/${{ inputs.service_name }}:latest
